#!/usr/bin/env python
#coding:utf8

import time
import datetime

def record_timer(mark=''):
		'''
		装饰器实现的时间计时器
		'''
		def tmp_func(func):
				def f(cls, *args, **kwargs):
						time_start = time.time()
						back = func(cls, *args, **kwargs)
						time_end = time.time()
						print '[{time}]{mark} <====> {cls_name}.{func_name} elapse: {passed}(ms)'.format(
										time=datetime.datetime.now().strftime("%Y-%m-%d %H:%m:%S"),
										mark=mark,  cls_name=cls.__class__.__name__,
										func_name=func.func_name, passed=1000*(time_end - time_start))
						return back
				return f
		return tmp_func
		

class People(object):
		def __init__(self, name):
				self.name = name
	
		@record_timer()
		def swim(self):
				time.sleep(2)
		
		
def main():
		me = People('gwecho')
		me.swim()
	
if __name__ == '__main__':
		main()
		
	
